openapi: 3.0.0
info:
  title: OPT120 Projeto Final API
  description: Esta é a documentação da API para o projeto final da disciplina OPT120.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local de desenvolvimento
paths:
  # Auth
  /login:
    $ref: './auth/login.yaml'

  # Users
  /api/users/new-admin:
    $ref: './users/newAdmin.yaml'
  /api/users/:id:
    $ref: './users/findUserById.yaml'
  
  # Rooms
  /api/rooms/:id/update:
    $ref: './rooms/updateRoom.yaml'
  /api/rooms/:
    $ref: './rooms/listRooms.yaml'
  /api/rooms/:id:
    $ref: './rooms/findRoomById.yaml'

  # Hours
  /api/hours/availability:
    $ref: './hours/listAvailabilityHours.yaml'
  /api/hours/del:
    $ref: './hours/removeHours.yaml'
